/**
 * Build a single-file executable.
 *
 * Node's Single Executable Application support needs one CommonJS file, so the
 * ESM sources are bundled with esbuild first. The operator console's three
 * static files are embedded as SEA assets rather than shipped alongside, so the
 * result really is one file with nothing to install next to it.
 *
 *   npm run build:exe
 *   -> dist-exe/gd-performance-shield.exe   (or ./gd-performance-shield on macOS/Linux)
 *
 * Steps: bundle -> generate the SEA blob -> copy the Node binary -> inject.
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'dist-exe');
const workDir = join(outDir, '.work');

const isWindows = process.platform === 'win32';
const exeName = isWindows ? 'gd-performance-shield.exe' : 'gd-performance-shield';
const exePath = join(outDir, exeName);
const bundlePath = join(workDir, 'bundle.cjs');
const blobPath = join(workDir, 'sea.blob');
const seaConfigPath = join(workDir, 'sea-config.json');

const uiDir = join(root, 'src', 'ui');
// Kept in step with UI_FILES in src/server/uiAssets.ts by hand: this script
// cannot import a TypeScript module. `app.js` imports `naming.js`, so a
// missing entry here breaks the console at load rather than at build.
const UI_FILES = ['index.html', 'app.js', 'naming.js', 'chart.js', 'styles.css'];

async function main() {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(workDir, { recursive: true });

  await bundle();
  writeSeaConfig();
  generateBlob();
  copyNodeBinary();
  injectBlob();

  const sizeMb = (statSync(exePath).size / (1024 * 1024)).toFixed(1);
  console.log(`\n  Built ${exePath} (${sizeMb} MB)`);
  console.log('  Single file - no Node, no node_modules, no separate assets.');
  console.log('  Requires adb on PATH (or ANDROID_HOME) for device profiling.\n');
}

/**
 * Bundle to CommonJS.
 *
 * `node:sea` is left external: it only exists inside a single executable, and
 * bundling it would break the on-disk build. Everything else is inlined.
 */
async function bundle() {
  console.log('  Bundling...');
  const result = await build({
    entryPoints: [join(root, 'src', 'cli', 'index.ts')],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    outfile: bundlePath,
    external: ['node:sea'],
    minify: false, // keep stack traces readable in a support situation
    sourcemap: false,
    logLevel: 'warning',
    define: { 'process.env.NODE_ENV': '"production"' },
    banner: {
      js: '// GD-PerformanceShield - single executable bundle. Generated by scripts/build-exe.mjs.',
    },
  });

  for (const warning of result.warnings) {
    console.warn(`  ! ${warning.text}`);
  }
  console.log(`    bundle: ${(statSync(bundlePath).size / (1024 * 1024)).toFixed(1)} MB`);
}

/** The console's files travel inside the binary as named SEA assets. */
function writeSeaConfig() {
  const assets = {};
  for (const file of UI_FILES) {
    const path = join(uiDir, file);
    if (!existsSync(path)) throw new Error(`Missing operator console asset: ${path}`);
    assets[file] = path;
  }

  writeFileSync(
    seaConfigPath,
    JSON.stringify(
      {
        main: bundlePath,
        output: blobPath,
        disableExperimentalSEAWarning: true,
        // The bundle is already a single flat file, so the V8 snapshot and code
        // cache buy little and both add build fragility across Node versions.
        useSnapshot: false,
        useCodeCache: false,
        assets,
      },
      null,
      2,
    ),
  );
}

function generateBlob() {
  console.log('  Generating SEA blob...');
  execFileSync(process.execPath, ['--experimental-sea-config', seaConfigPath], {
    stdio: 'inherit',
    cwd: workDir,
  });
}

function copyNodeBinary() {
  console.log('  Copying Node binary...');
  copyFileSync(process.execPath, exePath);

  // A copied binary keeps the original Authenticode signature, which no longer
  // matches once the blob is injected. Removing it up front avoids shipping a
  // file Windows reports as tampered with. signtool is part of the Windows SDK
  // and often absent, so this is best-effort.
  if (isWindows) {
    try {
      execFileSync('signtool', ['remove', '/s', exePath], { stdio: 'ignore' });
      console.log('    removed the existing signature');
    } catch {
      console.log('    signtool not available - leaving the signature in place (harmless)');
    }
  }
}

/**
 * Inject the blob with postject.
 *
 * postject's CLI entry point is invoked directly with the current Node rather
 * than through `npx`: recent Node refuses to spawn `.cmd` shims without a shell
 * (EINVAL), and going straight to the JS avoids both that and a shell.
 */
function injectBlob() {
  console.log('  Injecting...');

  const postjectCli = join(root, 'node_modules', 'postject', 'dist', 'cli.js');
  if (!existsSync(postjectCli)) {
    throw new Error(`postject not found at ${postjectCli}. Run: npm install -D postject`);
  }

  const args = [
    postjectCli,
    exePath,
    'NODE_SEA_BLOB',
    blobPath,
    '--sentinel-fuse',
    'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  ];
  if (process.platform === 'darwin') args.push('--macho-segment-name', 'NODE_SEA');

  execFileSync(process.execPath, args, { stdio: 'inherit', cwd: root });

  if (!isWindows) execFileSync('chmod', ['+x', exePath]);
}

main().catch((err) => {
  console.error(`\n  Build failed: ${err.message}\n`);
  process.exit(1);
});
