/**
 * Bundle the analysis server for the desktop app.
 *
 * Electron's main process loads CommonJS, while the sources are ESM, so esbuild
 * flattens `src/server/server.ts` and everything it imports into one CJS file
 * that exports `startServer`. Running the server in-process (rather than as a
 * child) means the app has one lifecycle to manage and no orphaned processes if
 * it is force-quit.
 *
 *   npm run build:desktop   -> desktop/build/server.cjs
 *   npm run dist:win        -> Windows installer + portable exe
 *   npm run dist:mac        -> macOS dmg + zip (must run on macOS)
 */
import { mkdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'desktop', 'build', 'server.cjs');

async function main() {
  rmSync(join(root, 'desktop', 'build'), { recursive: true, force: true });
  mkdirSync(dirname(outFile), { recursive: true });

  console.log('  Bundling the analysis server for Electron...');

  const result = await build({
    entryPoints: [join(root, 'src', 'server', 'server.ts')],
    bundle: true,
    platform: 'node',
    // Electron 33 ships Node 20; matching it avoids downlevelling syntax the
    // runtime supports natively.
    target: 'node20',
    format: 'cjs',
    outfile: outFile,
    // `electron` is provided by the runtime, `node:sea` never applies here.
    external: ['electron', 'node:sea'],
    minify: false, // keep stack traces readable when a studio reports a bug
    sourcemap: false,
    logLevel: 'error',
    define: { 'process.env.NODE_ENV': '"production"' },
    banner: {
      js: '// GD-PerformanceShield analysis server. Generated by scripts/build-desktop.mjs.',
    },
  });

  for (const warning of result.warnings) console.warn(`  ! ${warning.text}`);

  const sizeMb = (statSync(outFile).size / (1024 * 1024)).toFixed(1);
  console.log(`  Built ${outFile} (${sizeMb} MB)`);
}

main().catch((err) => {
  console.error(`\n  Desktop bundle failed: ${err.message}\n`);
  process.exit(1);
});
